---
- name: Ensure zsh dir exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/dotfiles/zsh"
    state: directory
    mode: '0755'

- name: Deploy .zshrc symlink
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/.zshrc"
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: link
    force: true

- name: Deploy .tmux.conf symlink
  ansible.builtin.file:
    src: "{{ lookup('env', 'HOME') }}/dotfiles/.tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
    state: link
    force: true

