---
- name: Ensure ~/.config exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory
    mode: '0755'

- name: Symlink nvim config dir
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/nvim"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    state: link
    force: true
